version: '3.6'
services:
  sonarqube:
    build:
      context: .
    stdin_open: true
    tty: true
    #environment:
    #  GITLAB_OMNIBUS_CONFIG: |
    #    external_url 'https://gitlab.example.com'
    #    # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:9000'
    #  - '443:443'
    #  - '22:22'
    volumes:
      - './conf/sonar.properties:/opt/sonarqube/conf/sonar.properties'
      - './logs:/opt/sonarqube/logs'
      #- ./data:/opt/sonarqube/data
      #- ./temp:/opt/sonarqube/temp
    #shm_size: '256m'
    networks:
      - network
  sonardb:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=78WGxJOFPFeEqqkE
      - POSTGRES_USER=sonarqubeadmin
      - POSTGRES_DB=sonarqubedb
    networks:
      - network

networks:
  network:
    driver: bridge
    name: sonarqube_network

